require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IngredientsNutrientsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # IngredientsNutrient. As you add validations to IngredientsNutrient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IngredientsNutrientsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ingredients_nutrients as @ingredients_nutrients" do
      ingredients_nutrient = IngredientsNutrient.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ingredients_nutrients)).to eq([ingredients_nutrient])
    end
  end

  describe "GET show" do
    it "assigns the requested ingredients_nutrient as @ingredients_nutrient" do
      ingredients_nutrient = IngredientsNutrient.create! valid_attributes
      get :show, {:id => ingredients_nutrient.to_param}, valid_session
      expect(assigns(:ingredients_nutrient)).to eq(ingredients_nutrient)
    end
  end

  describe "GET new" do
    it "assigns a new ingredients_nutrient as @ingredients_nutrient" do
      get :new, {}, valid_session
      expect(assigns(:ingredients_nutrient)).to be_a_new(IngredientsNutrient)
    end
  end

  describe "GET edit" do
    it "assigns the requested ingredients_nutrient as @ingredients_nutrient" do
      ingredients_nutrient = IngredientsNutrient.create! valid_attributes
      get :edit, {:id => ingredients_nutrient.to_param}, valid_session
      expect(assigns(:ingredients_nutrient)).to eq(ingredients_nutrient)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IngredientsNutrient" do
        expect {
          post :create, {:ingredients_nutrient => valid_attributes}, valid_session
        }.to change(IngredientsNutrient, :count).by(1)
      end

      it "assigns a newly created ingredients_nutrient as @ingredients_nutrient" do
        post :create, {:ingredients_nutrient => valid_attributes}, valid_session
        expect(assigns(:ingredients_nutrient)).to be_a(IngredientsNutrient)
        expect(assigns(:ingredients_nutrient)).to be_persisted
      end

      it "redirects to the created ingredients_nutrient" do
        post :create, {:ingredients_nutrient => valid_attributes}, valid_session
        expect(response).to redirect_to(IngredientsNutrient.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ingredients_nutrient as @ingredients_nutrient" do
        post :create, {:ingredients_nutrient => invalid_attributes}, valid_session
        expect(assigns(:ingredients_nutrient)).to be_a_new(IngredientsNutrient)
      end

      it "re-renders the 'new' template" do
        post :create, {:ingredients_nutrient => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ingredients_nutrient" do
        ingredients_nutrient = IngredientsNutrient.create! valid_attributes
        put :update, {:id => ingredients_nutrient.to_param, :ingredients_nutrient => new_attributes}, valid_session
        ingredients_nutrient.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ingredients_nutrient as @ingredients_nutrient" do
        ingredients_nutrient = IngredientsNutrient.create! valid_attributes
        put :update, {:id => ingredients_nutrient.to_param, :ingredients_nutrient => valid_attributes}, valid_session
        expect(assigns(:ingredients_nutrient)).to eq(ingredients_nutrient)
      end

      it "redirects to the ingredients_nutrient" do
        ingredients_nutrient = IngredientsNutrient.create! valid_attributes
        put :update, {:id => ingredients_nutrient.to_param, :ingredients_nutrient => valid_attributes}, valid_session
        expect(response).to redirect_to(ingredients_nutrient)
      end
    end

    describe "with invalid params" do
      it "assigns the ingredients_nutrient as @ingredients_nutrient" do
        ingredients_nutrient = IngredientsNutrient.create! valid_attributes
        put :update, {:id => ingredients_nutrient.to_param, :ingredients_nutrient => invalid_attributes}, valid_session
        expect(assigns(:ingredients_nutrient)).to eq(ingredients_nutrient)
      end

      it "re-renders the 'edit' template" do
        ingredients_nutrient = IngredientsNutrient.create! valid_attributes
        put :update, {:id => ingredients_nutrient.to_param, :ingredients_nutrient => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ingredients_nutrient" do
      ingredients_nutrient = IngredientsNutrient.create! valid_attributes
      expect {
        delete :destroy, {:id => ingredients_nutrient.to_param}, valid_session
      }.to change(IngredientsNutrient, :count).by(-1)
    end

    it "redirects to the ingredients_nutrients list" do
      ingredients_nutrient = IngredientsNutrient.create! valid_attributes
      delete :destroy, {:id => ingredients_nutrient.to_param}, valid_session
      expect(response).to redirect_to(ingredients_nutrients_url)
    end
  end

end
